### ISSUE TITLE
Aye.Warnings - chat bug

### ISSUE THREAD

**Issue by BLizzatron** [Benio101/Aye.Warnings#1]
Hello I do not understand why not works. Buff is, but if I get chat no. Play on ruRU client a screenshot for clarity.
http://imgur.com/uAmR5f9

**Comment by BLizzatron** [comment]
Although when I eat food and, click Ready check writes with (E) in chat it's okey. Then after receiving the buff, click Ready check, works one time then again this bug. With runes and flask no problem all ok.
http://imgur.com/tha5Z0P

**Comment by Benio101** [comment]
Hello, I've checked and I an confirm, that this is, because of checking for `Well Fed` buff, without taking into account possible localizations, in this case `ruRU` client. Checking for flask, runes and "eating" buff works, indded, language independent.

Reference: https://github.com/Benio101/Aye.Warnings/blob/master/utils/Buffs.lua#L128
I'll try to make it work fully, and independent of client localizations, propably within few hours.

Thanks for reporting. I'll add answer here once I push fixing commit.
Kee

**Comment by BLizzatron** [comment]
Thx a lot. I like your Addons due to large choice.
